### ISSUE TITLE
Sticky header distracts when reading an article

### ISSUE THREAD

**Issue by alexdev888** [indepth-dev/community#32]
Hello,
I find out that sticky header which appears when you scroll a bit on top is distracting when you read an article.
Sometimes you need to scroll a bit on top to se the code and this sticky header appears.

**Comment by maxkoretskyi** [comment]
Thanks for the suggestion, we'll try to think of a better UX pattern.

**Comment by alexdev888** [comment]
IMHO, I would go the "medium" way when content is aligned to center, no distraction things like sidebar, no popup, only what matter - content only!

**Comment by maxkoretskyi** [comment]
Yeah, we're trying our best to make content the king on the page, but still need to show other things like promotions etc. because the content is free.
